version: 2
dependencies:
  pre:
    - pip install pep8
jobs:
  build:
    working_directory: ~/python
    docker:
      - image: python:2.7
    steps:
      - run: pep8 *.py
      - run: python test_*.py
